# Generated by Django 5.1.6 on 2025-02-09 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='sales_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='銷售時間'),
        ),
        migrations.AddField(
            model_name='consumptionrecord',
            name='sold_item',
            field=models.CharField(default='Unknown', help_text='銷售品項', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='建立時間'),
        ),
    ]
