# Generated by Django 5.1.6 on 2025-02-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_consumptionrecord_sales_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(help_text='使用的積分數量')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, help_text='兌換時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
