# Generated by Django 5.1.6 on 2025-02-10 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_redemptionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(default=django.utils.timezone.now, help_text='同步時間')),
                ('status', models.CharField(choices=[('成功', '成功'), ('失敗', '失敗')], default='成功', max_length=20)),
                ('message', models.TextField(blank=True, help_text='同步結果描述', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consumptionrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='redemptionrecord',
            name='redeemed_at',
        ),
        migrations.AddField(
            model_name='redemptionrecord',
            name='redeemed_item',
            field=models.CharField(default='未指定', help_text='兌換品項', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemptionrecord',
            name='redemption_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='兌換時間'),
        ),
        migrations.AlterField(
            model_name='redemptionrecord',
            name='points_used',
            field=models.IntegerField(help_text='兌換使用的積分'),
        ),
    ]
