# Generated by Django 5.1.6 on 2025-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_googlesheetssynclog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrecord',
            name='redeemed_item',
            field=models.CharField(default='未指定', help_text='兌換品項', max_length=200),
        ),
    ]
