# Generated by Django 5.1.6 on 2025-02-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_redemptionrecord_redeemed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='積分到期時間', null=True),
        ),
    ]
